# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: phackt.fr:~#
email: phackt[AT]protonmail.com
description: "<h2>Development and infosec stuff!</h2>Enjoy!"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://phackt.fr" # the base hostname & protocol for your site
#url: "http://localhost:4000" # testing for localhost

#S ocial network
twitter_username: phackt_ul
github_username:  phackt

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# highlight
highlighter: rouge
permalink: /:title

#Excluded files
#exclude:
#  - docs
#  - CNAME
#  - Gemfile
#  - Rakefile
#  - README.md
#  - .gitignore
#  - .sass-cache
#  - Gemfile.lock
  
# Allowing post in the future (back to the future baby)
future: true

# Syntactically Awesome Style Sheets
# sass:
#   sass_dir: public/css
#   style: :compressed
